spring:
  application:
    name: MoneyOwl
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 3600000 # 30 minutes (30 * 60 * 1000)
  main:
    debug: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

---
# Local Server
spring:
  config:
    activate:
      on-profile: local

  #DB Url Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #Ollama AI LLM Config
  #  ai:
  #    ollama:
  #      base-url: http://localhost:11434
  #      chat:
  #        model: llama3.1 # Must support function calling
  #        options:
  #          temperature: 0.7 # Creativity level

  #Groq AI LLM Config
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: ${GROQ_MODEL_NAME}
          temperature: 0.7
  #JPA Properties
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        batch_size: 50
        batch_versioned_data: true
      order_inserts: true
      order_update: true
      generate_statistics: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  #Mail Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: true


# LOGGING #
#logging.level.org.springframework=DEBUG
#logging.level.com.finance.moneyowl=DEBUG
