CREATE SCHEMA moneyowl;

CREATE TABLE moneyowl.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    address TEXT NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    mob_no VARCHAR(20) NOT NULL,
    password VARCHAR(255) NULL,
    user_type VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP NULL,
    is_verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE moneyowl.roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    type VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE moneyowl.user_roles_mapping (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_mapping_user FOREIGN KEY (user_id)
        REFERENCES moneyowl.users (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT fk_mapping_role FOREIGN KEY (role_id)
        REFERENCES moneyowl.roles (role_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE moneyowl.portfolio (
    portfolio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equity NUMERIC(19,2) DEFAULT 0.00,
    debt NUMERIC(19,2) DEFAULT 0.00,
    cash_and_liquid NUMERIC(19,2) DEFAULT 0.00,
    gold NUMERIC(19,2) DEFAULT 0.00,
    real_estate NUMERIC(19,2) DEFAULT 0.00,
    fixed_income NUMERIC(19,2) DEFAULT 0.00,
    other_income NUMERIC(19,2) DEFAULT 0.00,

    user_id BIGINT UNIQUE NOT NULL,

    CONSTRAINT fk_portfolio_user FOREIGN KEY (user_id)
        REFERENCES moneyowl.users (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE moneyowl.liability (
    liability_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    liability_type VARCHAR(100) NOT NULL,
    liability_sub_type VARCHAR(100),

    start_date DATE NOT NULL,
    end_date DATE,
    roi NUMERIC(5,2) DEFAULT 0.00,
    duration NUMERIC(5,2),

    amount NUMERIC(19,2) NOT NULL DEFAULT 0.00,

    status VARCHAR(20) DEFAULT 'ACTIVE',

    user_id BIGINT NOT NULL,
    CONSTRAINT fk_liability_user FOREIGN KEY (user_id)
        REFERENCES moneyowl.users (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);